FROM node:20-alpine

WORKDIR /app

# Install dependencies first (better caching)
COPY package.json yarn.lock* ./
RUN yarn install

# Copy rest of the app
COPY . .

EXPOSE 3000

CMD ["yarn", "run", "start", "--host", "0.0.0.0"]
